### ISSUE TITLE
No accès to web interface

### ISSUE THREAD

**Issue by Lsm-CVX** [r3-team/r3#1]
Hi Gents, 
I am working on your piece of software to look if it could fit our needs (kind of tag generator shared). 

I tried to install it on a fresh Debian with Postgresql in local. (Debian 11 fresh install , no firewall, no specific installation as far as I could tell)

Connection to the database seems to the okay (no error) on both the ./r3 -run nor on the log of the database, however I can not connect to the web interface. 

I track down the problem to : 

failed to register listener for HTTP server, listen tcp 0.0.0.0:8080: bind: address already in use

I try the port 80, 443 and 8080 (none of them is used) : 

```
ei01:~# netstat -antu
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:5432          0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:57452         127.0.0.1:5432          ESTABLISHED
tcp        0      0 127.0.0.1:57806         127.0.0.1:5432          ESTABLISHED
tcp        0      0 127.0.0.1:5432          127.0.0.1:57806         ESTABLISHED
tcp        0      0 10.0.0.137:53304        199.232.178.132:80      TIME_WAIT  
tcp        0      0 127.0.0.1:57832         127.0.0.1:5432          ESTABLISHED
tcp        0      0 127.0.0.1:5432          127.0.0.1:57474         ESTABLISHED
tcp        0      0 127.0.0.1:5432          127.0.0.1:57832         ESTABLISHED
tcp        0      0 127.0.0.1:5432          127.0.0.1:57452         ESTABLISHED
tcp        0      0 127.0.0.1:57474         127.0.0.1:5432          ESTABLISHED
tcp        0      0 127.0.0.1:57830         127.0.0.1:5432          ESTABLISHED
tcp        0      0 127.0.0.1:5432          127.0.0.1:57830         ESTABLISHED
tcp6       0      0 :::8080                 :::*                    LISTEN     
tcp6       0      0 :::22                   :::*                    LISTEN     
tcp6       0      0 ::1:5432                :::*                    LISTEN     
tcp6       0      0 ::1:25                  :::*                    LISTEN     
udp6       0      0 ::1:55495               ::1:55495               ESTABLISHED 
```

(r3 is on 8080)

While I am writing this email, I just notice the IPV6 ... 

I disable fully the IPV6 stack and I got the 
failed to register listener for HTTP server, listen tcp 0.0.0.0:8080: bind: address already in use

I changed to 8088 (rebooted as well) 

At start, the service is not working : 

> * r3.service - Provides the REI3 platform components
>      Loaded: loaded (/etc/systemd/system/r3.service; enabled; vendor preset: enabled)
>      Active: inactive (dead) since Sat 2021-10-23 20:10:26 UTC; 8s ago
>     Process: 83 ExecStart=/root/r3 (code=exited, status=0/SUCCESS)
>    Main PID: 83 (code=exited, status=0/SUCCESS)
> 
> Oct 23 20:08:23 proxcluster-BMS-ei01 systemd[1]: Started Provides the REI3 platform components.
> Oct 23 20:08:23 proxcluster-BMS-ei01 rei3[83]: Starting service
> Oct 23 20:08:24 proxcluster-BMS-ei01 rei3[83]: failed to register listener for HTTP server, liste>
> Oct 23 20:10:26 proxcluster-BMS-ei01 systemd[1]: Stopping Provides the REI3 platform components...
> Oct 23 20:10:26 proxcluster-BMS-ei01 systemd[1]: r3.service: Succeeded.
> Oct 23 20:10:26 proxcluster-BMS-ei01 systemd[1]: Stopped Provides the REI3 platform components.
> 

A restart bring : 

> systemctl status r3.service
> * r3.service - Provides the REI3 platform components
>      Loaded: loaded (/etc/systemd/system/r3.service; enabled; vendor preset: enabled)
>      Active: active (running) since Sat 2021-10-23 20:10:51 UTC; 21s ago
>    Main PID: 363 (r3)
>       Tasks: 7 (limit: 9360)
>      Memory: 2.4M
>      CGroup: /system.slice/r3.service
>              `-363 /root/r3

Oct 23 20:10:51 proxcluster-BMS-ei01 systemd[1]: Started Provides the REI3 platform components.
Oct 23 20:10:51 proxcluster-BMS-ei01 rei3[363]: Starting service

Again IPV6 : 

> netstat -antu
> Active Internet connections (servers and established)
> Proto Recv-Q Send-Q Local Address           Foreign Address         State      
> tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN     
> tcp        0      0 127.0.0.1:5432          0.0.0.0:*               LISTEN     
> tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN     
> tcp        0      0 127.0.0.1:5432          127.0.0.1:59694         ESTABLISHED
> tcp        0      0 127.0.0.1:5432          127.0.0.1:59490         TIME_WAIT  
> tcp        0      0 127.0.0.1:59716         127.0.0.1:5432          ESTABLISHED
> tcp        0      0 127.0.0.1:59694         127.0.0.1:5432          ESTABLISHED
> tcp        0      0 127.0.0.1:5432          127.0.0.1:59472         TIME_WAIT  
> tcp        0      0 127.0.0.1:5432          127.0.0.1:59716         ESTABLISHED
> tcp6       0      0 :::22                   :::*                    LISTEN     
> tcp6       0      0 :::8088                 :::*                    LISTEN     
> udp        0      0 127.0.0.1:40567         127.0.0.1:40567         ESTABLISHED

// UPDATE //

I set the ip address in the config.json and it starts working !!

Sorry for the noice. I leave it in case it can be helpful for anybody.

**Comment by r3-gabriel** [comment]
Closed due to inactivity.
