### ISSUE TITLE
Missing message "bad identifier ..."

### ISSUE THREAD

**Issue by fabiograz** [r3-team/r3#13]
Hi, 
when create a new application, if name contains uppercase letter appear a this pop up
![J5Xr7qmwvH](https://user-images.githubusercontent.com/11799153/144269147-01264a2a-0e96-44c0-917d-2c10618e4464.png)

Message are not translated in Italian language, but I can't find it in "it_it" file. Such message isn't into en_en file also. I think it is hard coded in the application.

May you add in message files?
Thanks,
Fabio.

**Comment by r3-gabriel** [comment]
Hello Fabio,

You are right, this message is currently hard-coded. I will take a look at it.


Warm regards,

Gabriel

**Comment by r3-gabriel** [comment]
2.6 will introduce new error codes, which make it easier to deal with error messages from the backend on the frontend. This change also increases the number of translated error messages, including the one in this issue.
