### ISSUE TITLE
Modal subform

### ISSUE THREAD

**Issue by fabiograz** [r3-team/r3#14]
Hi,
in the team form, if I want to add a new member not in the list, when I click on the plus icon in the field the applicatin switch to a new form and all inputs are lost. In this case I expected a modal form in witch I can add a new member and then I can continue without any lost of datas.

How can I do it?

Thanks,
Fabio.

**Comment by r3-gabriel** [comment]
Hello Fabio,

We do not have this functionality yet. It is however on my own wish list and I hope we can make time for it soon.


Warm regards,

Gabriel

**Comment by r3-gabriel** [comment]
Good news: This feature is going to be part of the next minor release (2.6), which is currently being worked on.

**Comment by r3-gabriel** [comment]
2.6 released today, including options to open forms as "pop-ups". This enables opening up associated/new records for editing without loosing any inputs on the existing form. This should address this issue directly.

**Comment by r3-gabriel** [comment]
Closed due to inactivity.
