### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by fabiograz** [r3-team/r3#2]
Hi,
I found your project very interesting. So I've translated it in Italian language (see attached file).
I've created it_it file as copy of en_us in var/texts directory and translate it. Stop service and restart it (windows portable version 2.4.3), but language it_it not in Settings-Display-Language drop list. 

If I translate some core company application in Italian, I can select it_it in drop-list, but platform label are still in English also after service restart.

How can I add Italian translation to platform? 

Thanks,
Fabio.

[it_it.zip](https://github.com/r3-team/r3/files/7447565/it_it.zip)

**Comment by r3-gabriel** [comment]
Hello Fabio,

Currently the supported platform languages are hard-coded. We could make that dynamic but I think it might even be better if we include and ship more languages inside the default version of R3.

I´ve taken a look at the translated file and it looks good. Would you mind if we add it to the next release? It would then be included in every future version.

If we go that route you could then send a pull request for changes when you have them. We could also add a notice for authorship inside the translation file.

What do you think?


Warm regards,

Gabriel

**Comment by fabiograz** [comment]
Hi Gabriel,
I think it is a good option have more supported languages in the platform. So I open a pull request to submit the Italian translation.

Thanks.
Fabio.

**Comment by r3-gabriel** [comment]
Hello Fabio,

we are currently finishing up 2.5. If you use the 2.5 branch, your language file will be released soon.

Btw. we´ve moved the language files into `cache/captions/` in case you are wondering.

Warm regards,

Gabriel

**Comment by fabiograz** [comment]
Hi,
I've forked project and add Italian translation file to main branch and done a pull request for it. 
I've checked differences in 2.5 branch and upload a new translation file in it. I've done a pull request also.

Thanks,
Fabio

**Comment by r3-gabriel** [comment]
Hello Fabio,

I´ve merged your pull request for 2.5 and fixed some unescaped characters. When you do changes, you can use tools like [jsonlint.com](https://jsonlint.com/) to validate your file content. With the fixed characters, your language file is working properly in R3.

I am not sure if we release another 2.4 version. If we do, I will merge your pull request for 2.4 as well.

Thank you for your efforts!

Warm regards,

Gabriel

**Comment by fabiograz** [comment]
Sorry for any errors in the file. I didn't know [jsonlint.com ](url), next time I will check it before pull request.

Thanks,
Fabio.
