### ISSUE TITLE
Unable to download from the official website

### ISSUE THREAD

**Issue by NhanNTWPV** [r3-team/r3#28]
Not sure if this is the appropriate place to raise the issue but it's impossible to get the executables from [the download page](https://rei3.de/en/downloads). It seems to just return home when I click on any link, whether linux or windows.

**Comment by r3-gabriel** [comment]
We uploaded an older version file to the website by accident, breaking the main download links. It is fixed now.

Thank you for reporting this!

**Comment by NhanNTWPV** [comment]
The links are operational. Thx dude.
