### ISSUE TITLE
broken form builder filed data query in v3.2

### ISSUE THREAD

**Issue by gizocz** [r3-team/r3#30]
When add an "[1:n]" filed in form builder, then in column selector is a wrong relation.

How to reproduce:
Open "Assets IT" in builder -> Forms -> "smartphone" -> remove F24 ("[1:n] simcard.installed_in_smartphone") -> add the "[1:n] simcard.installed_in_smartphone" filed back inside the F23 container -> try to add an column, expected columns from "simcard" relation, but there are only columns from "smartphone" relations.

It works in REI3v3.1.3.

**Comment by r3-gabriel** [comment]
I was able to reproduce this issue as well:
![image](https://user-images.githubusercontent.com/91060542/210357486-fd6c8367-88d4-4fab-b3ee-ed51be392735.png)

This is definitely a bug - thank you for the report.

**Comment by r3-gabriel** [comment]
3.2.1 is now released with this issue fixed.
