### ISSUE TITLE
missing filed(s) in frontend function / Placeholders Form data fields selector

### ISSUE THREAD

**Issue by gizocz** [r3-team/r3#33]
I have two (or more) Relations with an attribute type "N:1" related to another Relation. These attributes have the **same name**. I have also a Form related to this another Relation. The form contains all "1:N" fields. The form has assigned a Frontend function. I can see only one "N:1" filed in the function placeholders form data fileds selector . If I rename the "N:1" attributes in Relations to different names, then all fileds will be in the fileds selector.

Tested in v3.1.3, v3.2.5 and v3.3.

**Comment by r3-gabriel** [comment]
Thank you very much for the report. Fix will follow soon.
