### ISSUE TITLE
Postgres with Secure Connection

### ISSUE THREAD

**Issue by openminder** [r3-team/r3#37]
Hi,

I find Rei3 very good so far, however I would like to connect to a PostgresSQL via SSL connection. Currently, however, it seems that sslmode=disabled is hard coded. See code snippet from db/db.go:
`conString := fmt.Sprintf("postgres://%s:%s@%s:%d/%s?sslmode=disable&connect_timeout=5",
		config.User, url.QueryEscape(config.Pass), config.Host, config.Port, config.Name)`

It would be great if you could enable SSL mode and specify a corresponding tls config in config.json if necessary.

All the best
Martin

**Comment by r3-gabriel** [comment]
Sure, we can add this option - the `config.json` file would be a good place for it as well.

What do you mean with TLS config? Any other relevant settings besides the SSL toggle?

**Comment by openminder** [comment]
It would be great to also add the possibility to hand over a TLS certificate for the secure connection. It is possible to hand over that certificate via the pgx client like that:

```
....
    rootCertPool := x509.NewCertPool()
    pem, err := ioutil.ReadFile(ca)
    if err != nil {
        panic(err)
    }

    if ok := rootCertPool.AppendCertsFromPEM(pem); !ok {
        panic("Failed to append PEM.")
    }

    connstring := fmt.Sprintf(
        "host=%s port=%d dbname=%s user=%s password=%s sslmode=verify-full target_session_attrs=read-write",
        host, port, dbname, user, password)

    connConfig, err := pgx.ParseConfig(connstring)
    if err != nil {
        fmt.Fprintf(os.Stderr, "Unable to parse config: %v\n", err)
        os.Exit(1)
    }

    connConfig.TLSConfig = &tls.Config{
        RootCAs:            rootCertPool,
        InsecureSkipVerify: true,
    }

    conn, err := pgx.ConnectConfig(context.Background(), connConfig)
    if err != nil {
        fmt.Fprintf(os.Stderr, "Unable to connect to database: %v\n", err)
        os.Exit(1)
    }

    defer conn.Close(context.Background())
....
```
See also: https://pkg.go.dev/github.com/jackc/pgx#ConnConfig for connection config
and https://pkg.go.dev/crypto/tls#Config for TLS config.

I hope I have explained this better now :-)

**Comment by r3-gabriel** [comment]
I assume, we are talking about the server certificate that the Postgres server uses. If that´s the case, I´d prefer to import the server certificate into the cert store of the connecting host (e. g. the REI3 server); then there is no need to put anything into the `config.json` file and the cert is where it should be (trusted certs).

Would that work for you?

An option for `InsecureSkipVerify` makes sense in any case, as not everybody has proper PKI - and better this than no encryption.

**Comment by openminder** [comment]
That sounds good to me. That's how it should work for me.
Thank you very much!

**Comment by r3-gabriel** [comment]
I´ve implemented your request. These are the new configuration options inside the `config.json` file:
`"db": { [...], "ssl": true, "sslSkipVerify": false }`

The service requires a restart after changing the config file. I´ve tested the feature with or without SSL verification and it works as expected: If the host can fully verify (by name and certificate chain) the database server certificate, you can just connect. If not, you can choose to use the `sslSkipVerify` option to ignore any issues and still connect via SSL.

The new feature is already published with [REI3.3.2](https://rei3.de/en/downloads).
