### ISSUE TITLE
Builder: New attribute form bug

### ISSUE THREAD

**Issue by patrik123git** [r3-team/r3#40]
Hi, 
there is an error in the New attribute form: when the value type is changed from Text to Number, Max. characters value stays set and saves even when Number (whole or decimal) Value type has in its form no option to set Max. characters value.

Steps to replicate this bug (REI3 3.4.1 and 3.4):
1. Create a new Relation.
2. Add a new attribute to Relation.
3. Set Max. characters value to some number, for example, 111.
4. Change Value type from Text (default) to Number.
5. Add an attribute name and save it.
6. This new number attribute has Max. length/Size set to 111 and this value cannot be changed.

Maybe there are some other situations where this bug occurs, so far I have tested only this case.

Regards,
Patrik L.

**Comment by r3-gabriel** [comment]
Yes, I can replicate this issue. The length option is not used for anything other than text/files attributes - but if its set before switching the attribute type, its still displayed and cannot be changed.

This issue will be fixed with the next release.

Thank you for the report, Patrick!

**Comment by r3-gabriel** [comment]
Fixed in REI3.4.2.
