### ISSUE TITLE
Docker compose errors

### ISSUE THREAD

**Issue by danny3n1tech** [r3-team/r3#46]
When attempting to install via docker compose I am getting the follow error. 
root@ssdnodes-6582dbb1769a2:~/docker/r3# docker-compose up
Building r3
[+] Building 2.5s (8/8) FINISHED                                                                                                                                              docker:default
 => CACHED [internal] load git source https://github.com/r3-team/r3_docker.git#main                                                                                                     0.3s
 => [internal] load metadata for docker.io/library/debian:stable-slim                                                                                                                   1.0s
 => [1/5] FROM docker.io/library/debian:stable-slim@sha256:4255c9f8a4d6e66488adc0c2084c99df44bda22849b21b3afc0e9746e9a0be18                                                             0.0s
 => https://rei3.de/downloads/REI3_3.6_x64_linux.tar.gz                                                                                                                                 0.4s
 => CACHED [2/5] RUN bash -c 'mkdir -p /opt/r3/data/{certificates,files,temp,transfer}'  && apt-get update  && apt-get install imagemagick ghostscript postgresql-client ca-certificat  0.0s
 => CACHED [3/5] WORKDIR /opt/r3                                                                                                                                                        0.0s
 => CACHED [4/5] ADD https://rei3.de/downloads/REI3_3.6_x64_linux.tar.gz .                                                                                                              0.0s
 => ERROR [5/5] RUN tar -xvf REI3_3.6_x64_linux.tar.gz r3 config_template.json  && sed -i "s/localhost/r3_db/g" config_template.json  && sed -i "s/443/80/g" config_template.json  &&   0.7s
------
 > [5/5] RUN tar -xvf REI3_3.6_x64_linux.tar.gz r3 config_template.json         && sed -i "s/localhost/r3_db/g" config_template.json    && sed -i "s/443/80/g" config_template.json     && chmod 755 r3 && chmod 644 config_template.json    && rm REI3_3.6_x64_linux.tar.gz:
0.572
0.572 gzip: stdin: not in gzip format
0.576 tar: Child returned status 1
0.576 tar: Error is not recoverable: exiting now
------
Dockerfile:28
--------------------
  27 |     ADD https://rei3.de/downloads/REI3_${r3_version}_${r3_os_arch}_linux.tar.gz .
  28 | >>> RUN tar -xvf REI3_${r3_version}_${r3_os_arch}_linux.tar.gz r3 config_template.json \
  29 | >>>      && sed -i "s/localhost/${r3_db_host}/g" config_template.json \
  30 | >>>      && sed -i "s/443/80/g" config_template.json \
  31 | >>>      && chmod 755 r3 && chmod 644 config_template.json \
  32 | >>>      && rm REI3_${r3_version}_${r3_os_arch}_linux.tar.gz
  33 |
--------------------
ERROR: failed to solve: process "/bin/sh -c tar -xvf REI3_${r3_version}_${r3_os_arch}_linux.tar.gz r3 config_template.json \t&& sed -i \"s/localhost/${r3_db_host}/g\" config_template.json \t&& sed -i \"s/443/80/g\" config_template.json \t&& chmod 755 r3 && chmod 644 config_template.json \t&& rm REI3_${r3_version}_${r3_os_arch}_linux.tar.gz" did not complete successfully: exit code: 2
ERROR: Service 'r3' failed to build : Build failed
root@ssdnodes-6582dbb1769a2:~/docker/r3#
I have attached an example for the yml file 
[docker-compose.yml.txt](https://github.com/r3-team/r3/files/14135542/docker-compose.yml.txt)

**Comment by r3-gabriel** [comment]
You seem to be referencing an outdated R3 release (R3.6). Make sure that you are using a version that is available under `All releases` on https://rei3.de/en/downloads. A current release is for example R3.7.

You can either set the release version in the file or via environment variable (s. [README](https://github.com/r3-team/r3_docker)).

**Comment by r3-gabriel** [comment]
No response, closing issue.
