### ISSUE TITLE
Build REI3 ./r3 -run  LINUX:failed to start embedded database, embedded database is only supported on Windows

### ISSUE THREAD

**Issue by yaoyingkeji** [r3-team/r3#48]
1. Install the latest version of [Golang](https://golang.org/dl/).
1. Go into the source code directory (where `r3.go` is located) and execute: `go build -ldflags "-X main.appVersion={YOUR_APP_VERSION}"`.
   * Replace `{YOUR_APP_VERSION}` with the version of the extracted source code. Example: `go build -ldflags "-X main.appVersion=2.5.1.2980"`
   * You can change the build version anytime. If you want to upgrade the major/minor version numbers however, you need to deal with upgrading the REI3 database (see `db/upgrade/upgrade.go`).
   * By setting the environment parameter `GOOS`, you can cross-compile for other systems (`GOOS=windows`, `GOOS=linux`, ...).

**I built it as described above and ran it under linux, prompting the following error?
 Does anyone know how to solve this problem?**

./r3 -run 
failed to start embedded database, embedded database is only supported on Windows
![图片](https://github.com/r3-team/r3/assets/93997433/c9dd11da-cae4-4482-bb4b-62807f0904b2)

**Comment by r3-gabriel** [comment]
Please check your `config.json` file for the parameter `db`->`embedded`.

If this parameter is set to `true`, REI3 will attempt to boot up the embedded database, which is only available on the packaged Windows version (standalone deployment).

**Comment by yaoyingkeji** [comment]
> Please check your `config.json` file for the parameter `db`->`embedded`.
> 
> If this parameter is set to `true`, REI3 will attempt to boot up the embedded database, which is only available on the packaged Windows version (standalone deployment).

Thank you very much, suggest adding to the documentation.

**Comment by r3-gabriel** [comment]
Thank you for the feedback. The correct config file template for dedicated deployment, which you are doing here, is available in the project directory with correct settings. But I´ll see where we could add another hint.

**Comment by yaoyingkeji** [comment]
I don't know what the problem is.
Error after running：
Where can I get this certificate?
data/certificates/cert.crt:


```
Starting web server for '0.0.0.0:9999'...
E: 17:56:46 open data/certificates/cert.crt: no such file or directory
Shutting down...

```

![图片](https://github.com/r3-team/r3/assets/93997433/5d643325-1efc-4c5a-af1a-33c697b04b7b)

**Comment by r3-gabriel** [comment]
If REI3 expects a certificate and cannot find one, it will create one itself. Does the directory from the command line output exist? If yes, can REI3 (eg. the user you use to start REI3 with) write to it?

Could you please share the contents of your `config.json` file? (after removing the passwords of course)

**Comment by yaoyingkeji** [comment]
The source code here does not include the empty directory "./data/certificates," which needs to be created manually. Then running "./r3 -run" will automatically create the "cert.crt" file.

----
However, another prompt has appeared:
When I built this using git clone, I encountered the following prompt when running it. Is this normal?
![图片](https://github.com/r3-team/r3/assets/93997433/a154a5cc-4e90-427a-b8b6-6cfc61752e87)

`config.json`
```
{
	"cluster": {
		"nodeId": "acad30b9-3dd7-4cc4-8a1c-c2f796107f22"
	},
	"db": {
		"host": "localhost",
		"port": 5432,
		"name": "rei3",
		"user": "postgres",
		"pass": "aa41deede",
		"embedded": false,
		"ssl": false,
		"sslSkipVerify": false
	},
	"paths": {
		"certificates": "data/certificates/",
		"embeddedDbBin": "pgsql16/bin/",
		"embeddedDbData": "data/database/",
		"files": "data/files/",
		"temp": "data/temp/",
		"transfer": "data/transfer"
	},
	"portable": false,
	"web": {
		"cert": "cert.crt",
		"key": "cert.key",
		"listen": "0.0.0.0",
		"port": 8899
	}
}
```

-----

Everything runs fine with the program I downloaded from here: “[https://rei3.de/downloads/REI3_3.7.2_x64_linux.tar.gz”](https://rei3.de/downloads/REI3_3.7.2_x64_linux.tar.gz%E2%80%9D)
![录屏_选择区域_20240229210059](https://github.com/r3-team/r3/assets/93997433/ef2093e6-8c89-47c6-9f0c-3df3d5de646a)

**Comment by r3-gabriel** [comment]
This error can pop-up regularly while you are using self-signed certificates. Which is the default, until you have supplied proper certificates.

The errors are harmless as they just say that your browser has issues trusting a self-signed cert until you have added a security exception.

**Comment by yaoyingkeji** [comment]
Thank you for your reply and explanation. How can I localize and publish the official app repository?
![截图_选择区域_20240301130639](https://github.com/r3-team/r3/assets/93997433/b444d275-a429-49b3-955b-c89bed98d638)

**Comment by r3-gabriel** [comment]
You might want to create new Github issues for different topics - this would make it easier to see and respond to your questions.

To the question at hand: You would need to host your own repository. With the app `REI3 Repository` you can upload your own application versions and write localized descriptions for each.
