### ISSUE TITLE
unable to install a package 

### ISSUE THREAD

**Issue by Al3x360** [r3-team/r3#53]
Hi, i have a problem with the docker installation, once installed and running, i cannot get any package to install i have this error : "open data/temp/9608818: no such file or directory"

to reproduce the bug i used the file provided by the docker compose file, did docker compose build r3 , then docker compose pull, then docker compose up . then i tried to install package from the admin panel, then i have the error.

the logs in portianer says : 

2024-05-27 09:38:22 websocket TRANSACTION 498217, request repoModule install failure (login ID 1), open data/temp/9306259: no such file or directory

i tried without portainer, the package installs fine. i think there is something wrong with my portainer stack config.

**Comment by r3-gabriel** [comment]
Hello,

The error message is pretty straightforward: The r3 service looks for a file in the directory `data/temp/`. The `data` directory must exist and be accessible for the r3 service, running in the corresponding container.

If you look into the shells of your individual containers, you should be able to check whether the directories are there and whether the r3 service places uploaded files there.

**Comment by r3-gabriel** [comment]
Close after 2 weeks with no response.
