### ISSUE TITLE
.tar.gz file corrupted ?

### ISSUE THREAD

**Issue by mgazzin** [r3-team/r3#55]
Hello, what happened with this file?

![immagine](https://github.com/r3-team/r3/assets/7835130/c4a239bc-b6b7-4b23-a5ae-ef907bdf92b5)

**Comment by r3-gabriel** [comment]
The file is not corrupt - it´s just not there anymore.
For patch releases, we only offer the latest versions. You can see, which versions are available under `All releases` on our [website](https://rei3.de/en/downloads).

**Comment by mgazzin** [comment]
weird because the file is not empty:

![immagine](https://github.com/r3-team/r3/assets/7835130/5de82b5c-6c5d-4657-a1a3-d23a3315d435)

however no problem, I am using now 3.7.6.
Thanks.

**Comment by r3-gabriel** [comment]
It´s not empty because the webserver defaults to the homepage if a resource is not available. So I guess you downloaded the start page :)
