### ISSUE TITLE
pdf_create generates at least two pages

### ISSUE THREAD

**Issue by TechInterMezzo** [r3-team/r3#56]
Taking the following code as an example:
```
app.pdf_create('test.pdf', 'a4', 'portrait', 10, 10, '', 'TEST', '', '').then(
	res => { }, // if success: return value in 'res'
	err => { }  // if error: error message in 'err'
);
```

It generates two pages but only one is expected. The second page is empty.

**Comment by r3-gabriel** [comment]
I was able to replicate the issue with your example.

The issue appears to be connected to the very small X/Y margins. If set them to 10/10, the header/footer/body elements cannot adjust correctly and wrap to the next page. If you apply more generous margins, like 40/40, the elements can work correctly and you get only 1 page.

**Comment by TechInterMezzo** [comment]
Thank you for the answer. That worked but I have also some other requirements. I guess in my case I will try to create an external PDF rendering service with REST API.

**Comment by r3-gabriel** [comment]
> That worked but I also have some other requirements. I guess in my case I will try to create an external PDF rendering service with REST API.

We know that the current PDF generation ability within r3 is quite limited. Tackling this is not on the immediate roadmap, but we would like to improve this in the long term.

**Comment by r3-gabriel** [comment]
The file backend of r3 is not exposed for such use cases. The only way to upload files to r3 is via its file upload handler, accessible via https://my-system/data/upload

But there is no official support or documentation available. How the handler works can be ascertained from the source code: https://github.com/r3-team/r3/blob/main/handler/data_upload/data_upload.go

You will need a valid token for this, which you can generate with any AUTH API call.

**Comment by TechInterMezzo** [comment]
> The only way to upload files to r3 is via its file upload handler, accessible via https://my-system/data/upload

This is working for me, regarding the file upload. But now I have to link the file to the specific relation. When I try the API created with the API builder and use the payload mentioned above I get the error "aborted api request, json: cannot unmarshal array into Go value of type types.DataSetFileChanges".

**Comment by r3-gabriel** [comment]
Good to hear :)
Just keep in mind that these are internal handlers, not exposed for regular use. This means that they can change without warning. We rarely have reasons to change them, but it´s a possibility.
