### ISSUE TITLE
Manipulating input fields (vue components)

### ISSUE THREAD

**Issue by TechInterMezzo** [r3-team/r3#58]
Is it possible to manipulate form fields with frontend functions?
I would like to change the color of the draw field when the form got loaded.
As the default value seems to be hardcoded I can't think of another way that wouldn't involve recompiling R3.
Or is there any system in place that allows to implement custom form fields?

**Comment by r3-gabriel** [comment]
There are multiple exposed calls to manipulate form fields via frontend functions:
![image](https://github.com/user-attachments/assets/6608438c-ab4f-41cc-b649-9a4409424f87)

Changing color of the draw input field is not available though.

There is currently no way to overwrite or introduce new custom form fields in the r3 default. Doing this would require custom code and is quite a lot of work.

**Comment by r3-gabriel** [comment]
Closing issue as there is no open task or request to answer.
