### ISSUE TITLE
Check for "any field changed" or "unsaved changes" in frontend

### ISSUE THREAD

**Issue by TechInterMezzo** [r3-team/r3#60]
Is it possible to check if there are any unsaved changes in a form?
I am using a custom frontend function that shouldn't be invokable if there are any unsaved changes, because the backend function it calls uses the data from the database.
app.record_save() seems to be async without a callback, so I can't use it to force saving the changes before calling the backend function. There could be a timing problem.

At the moment I am using form state conditions but to add every field one by one is very time consuming and easy to forget if new fields get added.

**Comment by r3-gabriel** [comment]
Currently you could only check all relevant inputs via form states, which is not very convenient.

We could add another form state condition, something like "form has any changes". This would return true if any field value has been changed.

Would that address your case?

We could also consider making app.record_save() return a promise, though that would probably take some work. Would that be helpful to you?

**Comment by TechInterMezzo** [comment]
Both additions would be great.
But "form has any changes" would already help me with my current case. I would remind the user to save the changes and enable the button for the custom function with the new form state.
The promise from record_save() could help me to automatically save changes before executing the next step. And I wouldn't have to let the user do it beforehand.

**Comment by r3-gabriel** [comment]
I just checked and unfortunately, adding new form state conditions requires a DB schema change, for which we need a minor release - this would need to wait for R3.9.

The promise would just be frontend and should be doable. I´ll add it to the wish list for R3.8.3.

**Comment by TechInterMezzo** [comment]
Besides getting and setting a value of a form field from frontend functions, it could also be useful to check if a value was changed. Or adding a function to check a form state by name.

**Comment by r3-gabriel** [comment]
Checking form states by name would be quite brittle - names can change and then you would have to know that you might have been referencing that name somewhere. States are generally quite hard to mix with event driven code like functions as states are constantly re-evaluated while functions are executed at specific events, which can be very unintuitive to troubleshoot.

To check for a changed field value should be easy enough - I think there is already a request for something like that. I´ll look at it for R3.8.3.

**Comment by r3-gabriel** [comment]
Another update: R3.8.3 will include the discussed app.get_field_value_changed() function to check whether the field value is currently marked as 'changed'.

**Comment by TechInterMezzo** [comment]
Regarding the usage of the form load event after saving. What about the (after) form save event? Does it get triggered when saving started or when it finished?

**Comment by r3-gabriel** [comment]
For every function event, you can click on the question mark to get the related info.
![grafik](https://github.com/user-attachments/assets/9fa6a089-6275-4f93-90c3-32a7c074398a)

In this case for the form save after event:
```
This event is executed after a user successfully executes a save of the form record. This works for both new & existing records.

Because a record is reloaded after a successful save, the event 'form loaded' is also executed after this event is finished.
```

In short: It occurs after saving completes. So yes, it would also be a good event to execute your backend call.

**Comment by r3-gabriel** [comment]
Closing issue as there is no open task or request to answer.
