### ISSUE TITLE
Docker: node number increases

### ISSUE THREAD

**Issue by TechInterMezzo** [r3-team/r3#62]
Everytime i restart my R3 docker container with docker compose up the node number increases.
Where is the node id/number saved?
Do I need to mount an additional volume to my docker container to make the node number persist between those restarts?

**Comment by r3-gabriel** [comment]
I have not had this issue before. Did you use the original compose file or did you make changes? If yes, please share your compose file.

**Comment by r3-gabriel** [comment]
I was initially confused what you meant with node number - but your explanation makes sense now. Thank you for the feedback.
