### ISSUE TITLE
Filters should start all "checked"

### ISSUE THREAD

**Issue by oriolgalceran** [r3-team/r3#66]
Currently, filters start out all "unchecked" and then you can choose the ones to show. Eventually if you want to show all of them you can either select all or clear them, which are equal states. I propose you adopt the excel scheme of having all filters preselected, and the user can uncheck them selectively or unselect them all to hide all items.

![Screenshot 2024-11-06 120854](https://github.com/user-attachments/assets/af28ad27-cff2-4efd-80c0-4ee3a7390b85)

**Comment by r3-gabriel** [comment]
I´ve had a look and checked against Excel / Libre Calc, in regards to how the behaviour is implemented there. And I agree that this would make it more consistent with how most people would interact with column filters.

No notes, will be implemented as requested. Thank you for the proposal.

**Comment by r3-gabriel** [comment]
Implemented in R3.9.2.
