### ISSUE TITLE
Attach files to rest call in backend function

### ISSUE THREAD

**Issue by TechInterMezzo** [r3-team/r3#68]
I know that it is possible to attach files with instance.mail_send but I would like to do the same with a rest call from the Postgres backend.
For example it would be useful to get the contents of the files and encode them with base64 to pass them as json encoded data.

**Comment by r3-gabriel** [comment]
With the current implementation, this would not be simple I think. The REST call is prepared within a backend function and then added to a spooler for a r3 server to execute. The DB system, where backend functions are executed, does not have access to the r3 file backend.

The r3 server could fetch files during execution of the REST call, but we would need to find a way to tell r3 how and where to attach files within the prepared message. Possibly via placeholders, but it would be cumbersome.

Do you have a suggestion?

**Comment by TechInterMezzo** [comment]
Is it possible to generate file links without involving the frontend? That way I could include them in the rest call and the target server could download the files. I could also let the rest server authenticate itself as an R3 user if necessary, I already did that for the opposite task of uploading files from the rust server to R3.

My other idea would require a lot more changes to the R3 server. There would be a new backend function similar to rest_call that sends multipart/form-data instead. The function parameters would include the same data as the file attachment in mail_send, plus a name for the form field. Maybe one could also add more form fields by passing json data to the function (and therefore the spooler) and the R3 server converts it to other multipart/form-data encoded fields in the request.

**Comment by r3-gabriel** [comment]
No need to prepare anything. Any file can be downloaded directly, provided:
* The authenticated user has permission.
* You have the attribute, record & file ID.

This is the generic download handler URL:
https://my-system.local/data/download/FILE.EXT?attribute_id=ATTRIBUTE_ID&file_id=FILE_ID&version=0&token=AUTH_TOKEN

You would execute an auth call to receive a valid token and then execute the download directly. For examples how an auth call looks, you can create a REST API in r3; the Builder shows all relevant calls for the API - auth calls always look the same.

To get the file IDs, you can use the backend function `instance.files_get()` while preparing your REST body.

**Comment by TechInterMezzo** [comment]
That should work. Thank you for describing a solution.
