### ISSUE TITLE
Check effective rights for attributes?

### ISSUE THREAD

**Issue by TechInterMezzo** [r3-team/r3#72]
Would it be possible to check the effective rights of a user for an attribute specified by it's ID?
It would help me a lot if I had a function in the backend that could check if the current user is ablo to read or write an attribute.
Currently my code has to check for the roles and I have to hardcode what rights I set for those roles.

**Comment by r3-gabriel** [comment]
Could you please help me understand, why you need to check this in backend functions? I can only assume this becoming relevant, if you are using a lot of backend-functions that are cross-calling each other and are accessible as frontend calls. Issue being that it becomes too much of a hassle to properly secure, who can execute which function when.

Is this correct or is there a different reason?

**Comment by TechInterMezzo** [comment]
That sums it up quite perfectly. I write many backend functions that get reused by other backend functions that are callable from the frontend. It's hard to make it flexible and secure at the same time.

**Comment by r3-gabriel** [comment]
While it is possible to create an instance function that answers this question for a combination of attribute and login ID, it would require a good amount of work to build and maintain. As I currently see it, this would be an esoterik feature that almost no one would use.

There is nothing speaking against this feature except that with how we need to prioritize our limited dev time, it would probably not be implemented in a long while as they are always more important features to add. Unless a customer would sponsor the dev time for this feature.

But I do not want to leave you empty-handed. It is possible to implement a function like that yourself, by creating a backend function that parses the DB schemas `instance` & `app` for the login permissions (eg. which roles are assigned, which roles can do what, which roles are inherited from other roles, etc.). This would not be part of the standard and could potentially break in the future, but it would work - and the corresponding entities (roles, access permissions, etc.) have not changed in many years and I am not aware of any plans of changing them anytime soon.

**Comment by TechInterMezzo** [comment]
Alright, thank you. Btw. I fully understand your circumstances for not implementing everything that gets suggested, especially from non paying users. I hope it's still okay to post my issues here, even if they are exotic and not gonna be resolved by official implementations. On the other side I will post my implementation when I am done. Just for the case that it could be helpful for someone else.

**Comment by r3-gabriel** [comment]
Please, always feel free to suggest, ask or report issues. Sometimes things are easy to implement or fit with other changes. Other times feature ideas are awesome and could benefit a lot of people. At the very least, this way we find out, what people need and can prioritize better.

In cases where things are hard and only benefit very few people, we need to be smart and work through other things first. Unfortunately our list of "other" things is multiple pages long and we are barely making a dent at the moment.
