### ISSUE TITLE
unknown field type, interface: 'types.FieldVariable'

### ISSUE THREAD

**Issue by TechInterMezzo** [r3-team/r3#77]
When I try to create a new form and chose to copy an existing form I get the error
`unknown field type, interface: 'types.FieldVariable'`

It only happens with forms showing variable fields.

**Comment by r3-gabriel** [comment]
That is definitely a bug. I´ll have a look. Thank you for reporting it.

**Comment by r3-gabriel** [comment]
Ok, found the issue and applied a [fix](https://github.com/r3-team/r3/commit/5326c916468e135ff9e1f63667543dd3186c97ba).
